- hosts: local
  vars:
    brew_install:
       - watch
       - docker
       - docker-machine
       - docker-compose
       - python
       - python3
       - vim
       - protobuf
       - postgresql
       - mc
       - npm
       - pv
       - graphviz
       - plantuml
       - mercurial
       - tree
       - ghc
  tasks:
    - name: Install packages with homebrew
      homebrew: name={{ item }} update_homebrew=yes
      with_items: "{{ brew_install }}"
    - name: link homebrew packages
      shell: brew link --overwrite {{ item }}
      with_items: "{{ brew_install }}"
    - name: install IPython
      sudo: yes
      shell: pip install -U ipython[all]
    - name: install IPython3
      sudo: yes
      shell: pip3 install -U ipython[all]
