- hosts: local
  vars:
    brew_install:
       - colordiff
       - watch
       - docker
       - docker-machine
       - docker-compose
       - python
       - python3
       - vim
       - protobuf
       - postgresql
       - mc
       - npm
       - pv
       - leiningen
       - ghc
       - graphviz
       - plantuml
       - mercurial
       - tree
       - ghostscript
       - ack
       - the_silver_searcher
       - Caskroom/cask/virtualbox
       - Caskroom/cask/virtualbox-extension-pack
       - bash-git-prompt
  pip_common_install:
       - ipython[all]
       - psycopg2
       - frosted
       - autopep8
  tasks:
    - name: Install packages with homebrew
      homebrew: name={{ item }} update_homebrew=yes
      with_items: "{{ brew_install }}"
    - name: link homebrew packages
      shell: brew link --overwrite {{ item }}
      with_items: "{{ brew_install }}"

    - name: install python2 packages
      sudo: yes
      shell: pip install -U {{ item }}
      with_items: "{{ pip_common_install }}"
    - name: install python3 packages
      sudo: yes
      shell: pip3 install -U {{ item }}
      with_items: "{{ pip_common_install }}"
