- hosts: local
  tasks:
    - name: install docker machine
      get_url:
        url=https://github.com/docker/machine/releases/download/v0.3.0/docker-machine_darwin-amd64
        dest=/usr/local/bin/docker-machine
        mode=a+x
